project:
  alias: inspec-k8s

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: inspec-notify

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true